# Generated by Django 5.2.7 on 2025-11-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ipswich_Retail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Coming soon...'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='images/'),
        ),
    ]
